console.log("i love javascript")
console.log("i love raectJS")
console.log("i love git")
console.log("i love web development")
console.log("i love developemnt")
console.log("i love the car driving")
console.log("i want to be the master in softwsre development")
console.log("i love javascript")
console.log("i love javascript")
console.log("i love javascript")
